name: Security Scan

on:
  workflow_dispatch:


jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
      
      - name: gitleak
        uses: gitleaks/gitleaks-action@v2


